
ifeq ($(CORE), ARMV8)
CCOMMON_OPT += -march=armv8-a
FCOMMON_OPT += -march=armv8-a
endif

ifeq ($(CORE), THUNDERX)
MYOPTS = -mcpu=cortex-a53
#MYOPTS = -mcpu=thunderx
# -funroll-loops
CCOMMON_OPT += $(MYOPTS)
FCOMMON_OPT += $(MYOPTS)
endif

